# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.26.0"
  summary: Multimodal Access and Interactive Data Representations
  python_check_max: "3.14"

recipe:
  name: py-maidr-split
  version: ${{ version }}

source:
  - target_directory: dist
    url: https://files.pythonhosted.org/packages/source/m/maidr/maidr-${{ version }}.tar.gz
    sha256: 0c15a645ce74ba7bdbef68e3847c79143a49441098d2982ae94043cf7d1effd2
  - target_directory: src
    url: https://github.com/xability/py-maidr/archive/refs/tags/v${{ version }}.tar.gz
    sha256: f024b64f43c0b2aaf28946fe89defc7c4e362ecdd64a88358ddc1e6362712ded

build:
  number: 0
  noarch: python

outputs:
  - package:
      name: py-maidr
    build:
      number: 0
      noarch: python
      script:
        - cd dist
        - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check --check-build-dependencies
    requirements:
      host:
        - hatchling
        - pip
        - python ${{ python_min }}.*
      run:
        - htmltools >=0.5
        - lxml >=5.1.0
        - mplfinance >=0.12.10b0
        - numpy >=1.26
        - python >=${{ python_min }}
        - wrapt >=1.16.0,<2
        - seaborn-base >=0.13
        - matplotlib-base >=3.8
        - scipy >=1.11
      run_constraints:
        - statsmodels >=0.14.4
    tests:
      - package_contents:
          strict: true
          site_packages:
            - maidr/**
            - maidr-${{ version }}.dist-info/**
      - python:
          imports: maidr
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*

  - package:
      name: py-maidr-with-altair
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("py-maidr", exact=True) }}
        - altair >=5.0
    tests:
      - python:
          imports: maidr
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*
    about:
      summary: ${{ summary }} (with [altair])

  - package:
      name: py-maidr-with-jupyter
    requirements:
      run:
        - ${{ pin_subpackage("py-maidr", exact=True) }}
        - ipykernel >=6.0.0
        - jupyter >=1.0.0,<2
    tests:
      - python:
          imports: maidr
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*
    about:
      summary: ${{ summary }} (with [jupyter])

  - package:
      name: py-maidr-with-plotly
    requirements:
      run:
        - ${{ pin_subpackage("py-maidr", exact=True) }}
        - plotly >=5.0
        - contourpy >=1.0.1
    tests:
      - python:
          imports: maidr
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*
    about:
      summary: ${{ summary }} (with [plotly])

  - package:
      name: py-maidr-with-shiny
    requirements:
      run:
        - ${{ pin_subpackage("py-maidr", exact=True) }}
        - shiny >=1.0
    tests:
      - python:
          imports: maidr
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*
    about:
      summary: ${{ summary }} (with [shiny])

  - package:
      name: py-maidr-with-streamlit
    requirements:
      run:
        - ${{ pin_subpackage("py-maidr", exact=True) }}
        - streamlit >=1.30
    tests:
      - python:
          imports: maidr
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*
    about:
      summary: ${{ summary }} (with [streamlit])

  - package:
      name: py-maidr-with-visualization
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("py-maidr", exact=True) }}
        - flask >=3.0.0
        - seaborn-base
        # constraint above
        - statsmodels
    tests:
      - python:
          imports: maidr
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*
    about:
      summary: ${{ summary }} (with [visualization])

  - package:
      name: py-maidr-with-all
    requirements:
      run:
        - ${{ pin_subpackage("py-maidr-with-altair", exact=True) }}
        - ${{ pin_subpackage("py-maidr-with-jupyter", exact=True) }}
        - ${{ pin_subpackage("py-maidr-with-plotly", exact=True) }}
        - ${{ pin_subpackage("py-maidr-with-shiny", exact=True) }}
        - ${{ pin_subpackage("py-maidr-with-streamlit", exact=True) }}
        - ${{ pin_subpackage("py-maidr-with-visualization", exact=True) }}
        - ${{ pin_subpackage("py-maidr", exact=True) }}
    tests:
      - python:
          imports: maidr
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*
      - files:
          source:
            - src/tests/
            - src/docs/
            - src/pyproject.toml
        requirements:
          run:
            - cssselect >=1.2
            - pytest >=7.3.2,<8
            - pytest-cov
            - pytest-mock >=3.12.0,<4
            - pytest-html
            - python ${{ python_min }}.*
            # uses deprecated assumptions in test, using version from `uv.lock`
            #   AttributeError: module 'plotly.graph_objects' has no attribute 'Scattermapbox'
            - if: match(version, "1.25.0.*")
              then:
                - plotly 6.7.0.*
        script:
          file: run_test.py
    about:
      summary: ${{ summary }} (with all [extras])

about:
  homepage: https://pypi.org/project/maidr
  summary: ${{ summary }}
  license: GPL-3.0-or-later
  license_file:
    - dist/LICENSE
    # TODO: js licenses?
  repository: https://github.com/xability/py-maidr
  documentation: https://py.maidr.ai

extra:
  feedstock-name: py-maidr
  recipe-maintainers:
    - bollwyvl
